services:
  ahorcado-angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18081:80"
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
