services:
  ahorcado-php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18082:80"
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/apache2
      - /var/lock/apache2
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
